services:
  backend-despachos:
    build: .
    container_name: backend-despachos
    ports:
      - "8081:8081"
    environment:
      DB_ENDPOINT: ${DB_ENDPOINT}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - despachos-data:/app/data
    restart: always

  backend-ventas:
    image: belruz/repo-backend-ventas:latest
    container_name: backend-ventas
    ports:
      - "8080:8080"
    environment:
      DB_ENDPOINT: ${DB_ENDPOINT}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ventas-data:/app/data
    restart: always

volumes:
  despachos-data:
  ventas-data: